"use client";

import { ChevronRight, HelpCircle } from "lucide-react";
import { useRouter } from "next/navigation";
import { use, useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { SurveyCardHeader } from "@/components/survey-card-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { api } from "@/lib/trpc/react";

type SectionFormData = {
  fixedScreeningQuestions: string[];
  screeningQuestions: string[];
  mainSurveyQuestions: string[];
};

type Props = {
  params: Promise<{
    id: string;
  }>;
};

const Page = ({ params }: Props) => {
  const router = useRouter();
  const { id } = use(params);
  const surveyId = Number(id);

  const [screeningQuestions, setScreeningQuestions] = useState<string[]>([]);
  const [mainSurveyQuestions, setMainSurveyQuestions] = useState<string[]>([]);

  const fixedScreeningQuestions = ["性別", "年齢", "居住地（都道府県単位）"];

  const { handleSubmit } = useForm<SectionFormData>();

  // 既存のセクションを取得
  const { data: sections, isLoading } = api.section.list.useQuery({
    surveyId,
  });

  // 調査情報を取得
  const { data: survey } = api.survey.getById.useQuery({
    id: surveyId,
  });

  // 各セクションの質問を取得
  const { data: questionsData } = api.question.listBySurvey.useQuery({
    surveyId,
  });

  // セクション同期のmutation
  const syncSections = api.section.sync.useMutation({
    onSuccess: () => {
      toast.success("セクションが更新されました");
      router.push(`/surveys/${id}/question/preview`);
    },
    onError: (error) => {
      toast.error(`更新に失敗しました: ${error.message}`);
    },
  });

  // 自動同期用（リダイレクトなし）
  const autoSyncSections = api.section.sync.useMutation({});

  // 既存のセクションデータをフォームに反映
  useEffect(() => {
    if (sections) {
      const screeningSections = sections
        .filter((s: any) => s.phase === "SCREENING")
        .map((s: any) => s.title);
      const mainSections = sections
        .filter((s: any) => s.phase === "MAIN")
        .map((s: any) => s.title);

      // 既存のセクションがある場合はそれを使用、なければデフォルト値を設定
      if (screeningSections.length > 0) {
        setScreeningQuestions(screeningSections);
      }
      if (mainSections.length > 0) {
        setMainSurveyQuestions(mainSections);
      }
    }
  }, [sections]);

  // 新規調査作成の内容に基づいてセクションを自動生成しDBに保存
  useEffect(() => {
    const run = async () => {
      if (
        survey &&
        sections &&
        sections.length === 0 &&
        !autoSyncSections.isPending
      ) {
        const autoGeneratedScreening = generateScreeningSections(survey);
        const autoGeneratedMain = generateMainSections(survey);
        setScreeningQuestions(autoGeneratedScreening);
        setMainSurveyQuestions(autoGeneratedMain);
        try {
          await autoSyncSections.mutateAsync({
            surveyId,
            screeningTitles: autoGeneratedScreening,
            mainTitles: autoGeneratedMain,
          });
        } catch {}
      }
    };
    run();
  }, [survey, sections, surveyId, autoSyncSections]);

  // 質問が無ければダミー設問を生成
  const seedMutation = api.question.seedForSurvey.useMutation({});
  useEffect(() => {
    if (questionsData && questionsData.length > 0) {
      const total = questionsData.reduce(
        (sum: number, s: any) => sum + (s.questions?.length || 0),
        0,
      );
      if (total === 0 && !seedMutation.isPending) {
        seedMutation.mutate({ surveyId });
      }
    }
  }, [questionsData, seedMutation, surveyId]);

  // スクリーニングセクションの自動生成
  const generateScreeningSections = (surveyData: any) => {
    const sections = [];

    // 基本属性確認（年齢、性別、居住地）
    if (surveyData.targetCondition) {
      sections.push("基本属性確認");
    }

    // 対象者条件確認
    if (surveyData.targetCondition) {
      sections.push("対象者条件確認");
    }

    // 職業・属性確認
    if (
      surveyData.targetCondition &&
      (surveyData.targetCondition.includes("職業") ||
        surveyData.targetCondition.includes("年収") ||
        surveyData.targetCondition.includes("学歴"))
    ) {
      sections.push("職業・属性確認");
    }

    // 家族構成確認
    if (
      surveyData.targetCondition &&
      (surveyData.targetCondition.includes("家族") ||
        surveyData.targetCondition.includes("結婚") ||
        surveyData.targetCondition.includes("子ども"))
    ) {
      sections.push("家族構成確認");
    }

    return sections.length > 0 ? sections : ["基本属性確認", "対象者条件確認"];
  };

  // 本調査セクションの自動生成
  const generateMainSections = (surveyData: any) => {
    const sections = [];

    // 利用状況・体験
    if (
      surveyData.analysisCondition &&
      (surveyData.analysisCondition.includes("利用") ||
        surveyData.analysisCondition.includes("満足度") ||
        surveyData.analysisCondition.includes("体験"))
    ) {
      sections.push("利用状況・体験");
    }

    // 購買行動・決定要因
    if (
      surveyData.analysisCondition &&
      (surveyData.analysisCondition.includes("購買") ||
        surveyData.analysisCondition.includes("決定要因") ||
        surveyData.analysisCondition.includes("行動"))
    ) {
      sections.push("購買行動・決定要因");
    }

    // ブランド評価・認知
    if (
      surveyData.analysisCondition &&
      (surveyData.analysisCondition.includes("ブランド") ||
        surveyData.analysisCondition.includes("認知") ||
        surveyData.analysisCondition.includes("評価"))
    ) {
      sections.push("ブランド評価・認知");
    }

    // 今後の利用意向
    if (
      surveyData.analysisCondition &&
      (surveyData.analysisCondition.includes("今後の") ||
        surveyData.analysisCondition.includes("利用意向") ||
        surveyData.analysisCondition.includes("改善要望"))
    ) {
      sections.push("今後の利用意向");
    }

    // 競合比較・差別化
    if (
      surveyData.analysisCondition &&
      (surveyData.analysisCondition.includes("競合") ||
        surveyData.analysisCondition.includes("差別化") ||
        surveyData.analysisCondition.includes("比較"))
    ) {
      sections.push("競合比較・差別化");
    }

    return sections.length > 0
      ? sections
      : ["利用状況・体験", "今後の利用意向"];
  };

  const onSubmit = async (_data: SectionFormData) => {
    try {
      await syncSections.mutateAsync({
        surveyId,
        screeningTitles: screeningQuestions,
        mainTitles: mainSurveyQuestions,
      });
    } finally {
      router.push(`/surveys/${surveyId}/question/preview`);
    }
  };

  // 質問タイプ表示は未使用のため削除

  if (isLoading) {
    return (
      <div className="flex flex-col w-full">
        <SurveyCardHeader
          workingTitle="読み込み中..."
          currentStep={1}
          surveyId={surveyId}
        />
        <div className="flex flex-col w-full items-center gap-6 p-6 bg-[#ffffff] rounded-b-lg shadow-main-bg">
          <div className="animate-pulse">
            <div className="h-8 bg-gray-200 rounded w-64 mb-4" />
            <div className="h-96 bg-gray-200 rounded w-full" />
          </div>
        </div>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col w-full">
      <SurveyCardHeader
        workingTitle={survey?.title || "セクションの設定"}
        currentStep={1}
        surveyId={surveyId}
      />
      <div className="flex flex-col w-full items-center gap-6 p-6 bg-[#ffffff] rounded-b-lg shadow-main-bg">
        {/* Header Section */}
        <header className="flex items-start justify-center gap-4 w-full">
          <div className="w-2 h-6 bg-[#60adc2]" />
          <div className="flex flex-col items-start gap-4 flex-1">
            <div className="flex items-center gap-2">
              <h2 className="text-lg font-bold text-[#333333] whitespace-nowrap">
                セクション入力
              </h2>
            </div>
          </div>
        </header>

        <div className="flex flex-col items-start gap-2 px-6 py-0 w-full rounded overflow-hidden">
          <div className="w-full">
            <p className="text-sm font-medium text-[#333333]">
              調査票の大まかな項目（セクション）を設定してください。
            </p>
            <p className="text-sm font-medium text-[#333333]">
              スクリーニング設問・本調査設問とも、ここまでに入力した内容からあらかじめ推奨される項目が設定されます。
            </p>
            <p className="text-sm font-medium text-[#333333]">
              <span className="inline-flex items-center whitespace-nowrap">
                調査AI
                <HelpCircle className="w-5 h-5 text-gray-400" />
                と相談しながら設定することもできます
              </span>
            </p>
          </div>
        </div>

        <Card className="w-full">
          <CardContent className="p-6">
            <div className="flex items-center gap-2 mb-4">
              <h2 className="text-lg font-semibold text-gray-800">
                スクリーニング設問【固定】
              </h2>
              <HelpCircle className="w-5 h-5 text-gray-400" />
            </div>

            <div className="bg-gray-50 rounded-lg p-4">
              <div className="space-y-2">
                {fixedScreeningQuestions.map((question, index) => (
                  <div key={index} className="text-gray-700">
                    {question}
                  </div>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Screening Questions */}
        <Card className="w-full">
          <CardContent className="p-6">
            <div className="flex items-center gap-2 mb-4">
              <h2 className="text-lg font-semibold text-gray-800">
                スクリーニング設問
              </h2>
              <HelpCircle className="w-5 h-5 text-gray-400" />
            </div>

            <div className="flex flex-col items-end gap-2 w-full">
              <div className="flex flex-row items-stretch gap-2 w-full">
                <textarea
                  value={screeningQuestions.join("\n")}
                  onChange={(e) => {
                    const questions = e.target.value
                      .split("\n")
                      .filter((q) => q.trim() !== "");
                    setScreeningQuestions(questions);
                  }}
                  className="flex items-center px-4 py-3 w-full bg-white rounded border-2 border-solid border-[#dcdcdc] shadow-[0px_0px_8px_0px_rgba(0,0,0,0.04)] text-sm font-medium text-[#333333] placeholder:text-[#ababab] placeholder:text-base placeholder:font-normal resize-none focus:outline-none focus:border-[#138FB5] min-h-[120px]"
                  placeholder="スクリーニング設問を入力してください。新しい行で項目を区切ってください。"
                  style={{
                    fontFamily: "Noto Sans JP",
                    lineHeight: "1.714",
                  }}
                />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Main Survey Questions */}
        <Card className="w-full">
          <CardContent className="p-6">
            <div className="flex items-center gap-2 mb-4">
              <h2 className="text-lg font-semibold text-gray-800">
                本調査設問
              </h2>
              <HelpCircle className="w-5 h-5 text-gray-400" />
            </div>

            <div className="flex flex-col items-end gap-2 w-full">
              <div className="flex flex-row items-stretch gap-2 w-full">
                <textarea
                  value={mainSurveyQuestions.join("\n")}
                  onChange={(e) => {
                    const questions = e.target.value
                      .split("\n")
                      .filter((q) => q.trim() !== "");
                    setMainSurveyQuestions(questions);
                  }}
                  className="flex items-center px-4 py-3 w-full bg-white rounded border-2 border-solid border-[#dcdcdc] shadow-[0px_0px_8px_0px_rgba(0,0,0,0.04)] text-sm font-medium text-[#333333] placeholder:text-[#ababab] placeholder:text-base placeholder:font-normal resize-none focus:outline-none focus:border-[#138FB5] min-h-[180px]"
                  placeholder="本調査設問を入力してください。新しい行で項目を区切ってください。"
                  style={{
                    fontFamily: "Noto Sans JP",
                    lineHeight: "1.714",
                  }}
                />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Continue Button */}
        <div className="flex justify-center pt-6">
          <Button
            type="submit"
            className="bg-gray-600 hover:bg-gray-700 text-white px-8 py-4 h-14 rounded-full text-lg"
            size="lg"
            disabled={syncSections.isPending}
          >
            {syncSections.isPending ? "更新中..." : "調査票設問の設定に進む"}
            {!syncSections.isPending && (
              <ChevronRight className="w-5 h-5 ml-2" />
            )}
          </Button>
        </div>
      </div>
    </form>
  );
};

export default Page;
