steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-poc/survey-poc:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-poc/survey-poc:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'survey-poc'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-poc/survey-poc:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,DATABASE_URL=file:./packages/database/dev.db,BASIC_AUTH_USER=cmgadmin,BASIC_AUTH_PASSWORD=crossadmin'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/survey-poc/survey-poc:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY 