steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/survey-top-new/survey-top-new:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/survey-top-new/survey-top-new:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'survey-new-top'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/survey-top-new/survey-top-new:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '100'
      - '--set-env-vars'
      - 'NODE_ENV=production,DB_PROVIDER=bigquery,NEXT_PUBLIC_DB_PROVIDER=bigquery,BQ_PROJECT_ID=viewpers,BQ_DATASET=surveybridge_db,BQ_LOCATION=US,READONLY=false,NEXT_PUBLIC_READONLY=false,BASIC_AUTH_USER=cmgadmin,BASIC_AUTH_PASSWORD=crossadmin'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/survey-top-new/survey-top-new:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY 